### PR TITLE
Revert 'remove script' and fix the Dockerfile

### LINKED ISSUE #78: Tag Images for openshift-client Task
Currently, the `openshift-client` task uses a tag of [latest](https://github.com/tektoncd/catalog/blob/master/openshift-client/openshift-client-task.yaml#L15) for its image. It would be a better practice to tag the image based on the version of Tekton pipelines the task would work with and explicitly call out what the version tag is for the task as opposed to using the `latest` tag.

There should be documentation on the available tags and how those tags correspond to certain versions of Tekton pipelines/the task. The previous versions of the task should also be archived and use the appropriate image tag.

This issue is in response to #74 where the task was updated for a new version of the OpenShift Tekton operator that is actually not available yet. I would like to ask that this task not be updated until the new version of an operator is available in the future.

### PR DESCRIPTION
**Pull request by piyush-garg**
This is breaking the backward compatibility, better release
a branch for 0.5 and then update the tasks

This change will fix the issue of client
task giving error on tekton 0.5.0

Also, tag the image with the pipeline version
in spite of always latest

Fix #78

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

File: openshift-client/script.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#!/bin/bash
+
+set -e
+
+command="/usr/local/bin/oc-origin"
+
+for args in "$@"; do
```
Comment (ImJasonH) [inline openshift-client/script.sh]: Is this necessary due to a deficiency/bug in array-type param handling? This is pretty gross, and I'd love to not need it.

Comment (piyush-garg) [reply openshift-client/script.sh]: this we are doing for the previous tekton version, we may tag this to use with previous tekton pipeline, and update this without a script for current tekton version i.e. 0.6 as we have provided the feature of array type params.
